name: medi_connect
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

  image_picker: ^1.0.4




 
   


  # Íconos de Cupertino para iOS
  cupertino_icons: ^1.0.8

  # Manejo de estado
  provider: ^6.0.5

  # Firebase
  firebase_core: ^3.12.0  # Reemplaza con la última versión estable
  firebase_auth: ^5.5.0  # Reemplaza con la última versión estable
  cloud_firestore: ^5.6.4  # Reemplaza con la última versión estable

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter recomendado por Flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

